/**
 * Optimized Image Utilities
 *
 * Provides helpers to generate srcset and picture element data
 * from the image manifest created by scripts/optimize-images.ts
 */

// Import manifest at build time (will be generated by prebuild script)
let manifest: ImageManifest | null = null;

interface ImageVariant {
  width: number;
  format: string;
  path: string;
  size: number;
}

interface ImageManifest {
  [originalPath: string]: {
    original: string;
    width: number;
    height: number;
    aspectRatio: number;
    variants: ImageVariant[];
    srcset: {
      avif: string;
      webp: string;
      jpg: string;
    };
  };
}

interface OptimizedImageData {
  src: string;
  srcset: {
    avif: string;
    webp: string;
    jpg: string;
  };
  width: number;
  height: number;
  aspectRatio: number;
  sizes: string;
}

// Default sizes attribute for responsive images
const DEFAULT_SIZES = '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';

/**
 * Load the image manifest
 * Called once at build time
 */
async function loadManifest(): Promise<ImageManifest> {
  if (manifest) return manifest;

  try {
    // Dynamic import of JSON manifest
    const data = await import('../data/image-manifest.json');
    manifest = data.default as ImageManifest;
    return manifest;
  } catch {
    // Manifest doesn't exist yet (first build or dev mode)
    console.warn('Image manifest not found. Run `npm run optimize-images` first.');
    return {};
  }
}

/**
 * Get optimized image data for a given image path
 *
 * @param imagePath - Original image path (e.g., '/images/uploads/photo.jpg')
 * @param sizes - Custom sizes attribute (optional)
 * @returns Optimized image data or fallback to original
 */
export async function getOptimizedImage(
  imagePath: string,
  sizes: string = DEFAULT_SIZES
): Promise<OptimizedImageData> {
  const imageManifest = await loadManifest();
  const imageData = imageManifest[imagePath];

  if (!imageData) {
    // Fallback to original image if not in manifest
    return {
      src: imagePath,
      srcset: { avif: '', webp: '', jpg: '' },
      width: 0,
      height: 0,
      aspectRatio: 1,
      sizes,
    };
  }

  // Get the best fallback src (1200px WebP or original)
  const fallbackVariant = imageData.variants.find(
    v => v.format === 'webp' && v.width === 1200
  ) || imageData.variants.find(
    v => v.format === 'jpg' && v.width === 1200
  );

  return {
    src: fallbackVariant?.path || imagePath,
    srcset: imageData.srcset,
    width: imageData.width,
    height: imageData.height,
    aspectRatio: imageData.aspectRatio,
    sizes,
  };
}

/**
 * Synchronous version for use in component frontmatter
 * Requires manifest to be pre-loaded
 */
export function getOptimizedImageSync(
  imagePath: string,
  sizes: string = DEFAULT_SIZES
): OptimizedImageData {
  if (!manifest) {
    // Return fallback if manifest not loaded
    return {
      src: imagePath,
      srcset: { avif: '', webp: '', jpg: '' },
      width: 0,
      height: 0,
      aspectRatio: 1,
      sizes,
    };
  }

  const imageData = manifest[imagePath];

  if (!imageData) {
    return {
      src: imagePath,
      srcset: { avif: '', webp: '', jpg: '' },
      width: 0,
      height: 0,
      aspectRatio: 1,
      sizes,
    };
  }

  const fallbackVariant = imageData.variants.find(
    v => v.format === 'webp' && v.width === 1200
  ) || imageData.variants.find(
    v => v.format === 'jpg' && v.width === 1200
  );

  return {
    src: fallbackVariant?.path || imagePath,
    srcset: imageData.srcset,
    width: imageData.width,
    height: imageData.height,
    aspectRatio: imageData.aspectRatio,
    sizes,
  };
}

/**
 * Pre-load manifest for synchronous access
 * Call this at the start of build
 */
export async function preloadManifest(): Promise<void> {
  await loadManifest();
}

/**
 * Generate sizes attribute for common use cases
 */
export const imageSizes = {
  // Full width on mobile, constrained on larger screens
  hero: '100vw',
  // Card in grid (responsive columns)
  card: '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw',
  // Feed layout (centered, max-width constrained)
  feed: '(max-width: 640px) 100vw, (max-width: 1200px) 80vw, 900px',
  // Thumbnail
  thumbnail: '(max-width: 640px) 50vw, 200px',
  // Gallery grid
  gallery: '(max-width: 640px) 100vw, (max-width: 1024px) 33vw, 25vw',
};
